name: Seek
description: Execute 'make seek' and 'make diff' commands
inputs:
  path:
    description: Path to Service
    required: true

runs:
  using: "composite"
  steps:
    - name: ⚙︎ Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.0

    - name: ⬇️ Install gotestsum
      shell: bash
      run: |
        go install gotest.tools/gotestsum@v1.12.0

    - name: ⚙︎ Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: ⬇️ Install AWS CDK
      run: npm install -g aws-cdk
      shell: bash

    - name: 🔎 Seek
      run: make seek --directory ${{ inputs.path }}
      shell: bash

    - name: 🧬 Diff
      shell: bash
      run: |
        make diff --directory ${{ inputs.path }} > diff.txt
        if [ -s diff.txt ]; then
          gh pr comment ${{ github.event.number }} --body "$(printf '```\n%s\n```' "$(cat diff.txt)")"
          exit 0
        else
          echo "❌ No CDK Diff found"
        fi
