name: Seek
description: Execute 'make seek' and 'make diff' commands
inputs:
  path:
    description: Path to Service
    required: true

runs:
  using: "composite"
  steps:
    - name: ⚙︎ Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.0

    - name: ⬇️ Install gotestsum
      shell: bash
      run: |
        go install gotest.tools/gotestsum@v1.12.0

    - name: ⚙︎ Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: ⬇️ Install AWS CDK
      run: npm install -g aws-cdk
      shell: bash

    - name: 🔎 Seek
      shell: bash
      run: make seek --directory ${{ inputs.path }}

    - name: 🧬 Diff
      shell: bash
      run: |
        cd ${{ inputs.path }}/stack; \
        cdk diff --no-change-set --quiet --no-color > output.txt 2>&1; \
        awk '/Resources/{flag=1; print; next} /Number of stacks/{flag=0} flag' output.txt > resources_output.txt; \
        if [ -s diff.txt ]; then
          gh pr comment ${{ github.event.number }} --body "$(printf '### Changes Summary ✨\n' "$(cat resources_output.txt)")"
          exit 0
        else
          echo "❌ No CDK Diff found"
        fi
