name: "Deploy"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    
concurrency:
  group: "deploy-${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}"
  
permissions:
  contents: read
  id-token: write

env:
  CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
  CDK_DEFAULT_REGION: sa-east-1

jobs:
  Check:
    name: Check
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
      - run: go test -v ./...
      - run: cdk synth --all
      - run: cdk doctor
      - run: cdk diff --all

  Deploy:
    name: Deploy cdk
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
      - run: go test -v ./...
      - name: cdk deploy
        run: |
            cdk deploy --all --ci --require-approval never --trace
