name: "Deploy"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    
concurrency:
  group: "deploy-${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}"
  
permissions:
  contents: read
  id-token: write

env:
  CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
  CDK_DEFAULT_REGION: sa-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  Check:
    name: Check
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm install -g aws-cdk
      - run: go test -v ./...
      - run: cdk synth --all
      - run: cdk doctor
      - run: cdk diff --all

  Deploy:
    name: Deploy cdk
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm install -g aws-cdk
      - run: go test -v ./...
      - name: cdk deploy
        run: |
            cdk bootstrap
            cdk deploy --all --ci --require-approval never --trace
